// Generated by ReScript, PLEASE EDIT WITH CARE


var ObserverEntry = {};

var ObserverInit = {};

var Observer = {};

var $$DOMRect;

export {
  $$DOMRect ,
  ObserverEntry ,
  ObserverInit ,
  Observer ,
  
}
/* No side effect */
