// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

console.log(DOMRect.fromRect(5.3, 5.2, undefined, undefined));

var observer = new IntersectionObserver((function (entries) {
        if (entries.length !== 1) {
          return ;
        }
        var head = entries[0];
        console.log(head.intersectionRatio.y);
        console.log(head.intersectionRatio.x);
        console.log(head.intersectionRatio.width);
        console.log(head.intersectionRatio.height);
        console.log(head.intersectionRatio.top);
        console.log(head.intersectionRatio.right);
        console.log(head.intersectionRatio.bottom);
        console.log(head.intersectionRatio.left);
        console.log(head.intersectionRatio);
        
      }));

observer.observe(undefined);

observer.unobserve(undefined);

Belt_Array.map(observer.takeRecords(), (function (prim) {
        console.log(prim);
        
      }));

observer.disconnect();

export {
  observer ,
  
}
/*  Not a pure module */
