// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactFetch from "react-fetch";

var url = "https://api.github.com/v3/user/ri7nz";

var data = ReactFetch.fetch(url).json();

ReactFetch.preload(url);

export {
  url ,
  data ,
  
}
/* data Not a pure module */
