name: build testing
on:
  push:
    branches: [main, release, rc]
  pull_request:
    branches: [main, release, rc]
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: ["12"]
    name: Node version ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: yarn run build
